var data=[
    {
        "student_name":"Aaliyan Amir",
        "class":"9c",
        "father_name":"Amir Nizami",
        "contact":"03456025527",
        "group":"Computer Science",
        "gender":"Male",
        "profile":"",
    },
    {
        "student_name":"Waqas Zmeer",
        "class":"9b",
        "father_name":"Zameer Ahmed",
        "contact":"03456025527",
        "group":"Biology",
        "gender":"Male",
        "profile":"",
    },
    {
        "student_name":"Wareesha Khashif",
        "class":"9c",
        "father_name":"Kashisf Qureshi",
        "contact":"03456025527",
        "group":"Medical",
        "gender":"Female",
        "profile":"",
    },
    {
        "student_name":"Ammar Mazhar",
        "class":"9c",
        "father_name":"Mazhar Shaikh",
        "contact":"03456025527",
        "group":"Humanity",
        "gender":"Male",
        "profile":"",
    },
    {
        "student_name":"Khazina Kiran",
        "class":"9c",
        "father_name":"Umair Siddique",
        "contact":"03456025527",
        "group":"Humanity",
        "gender":"Female",
        "profile":"",
    },
    {
        "student_name":"Abdul Basit",
        "class":"9c",
        "father_name":"Abdul Majeed",
        "contact":"03456025527",
        "group":"Computer Science",
        "gender":"Male",
        "profile":"",
    },
    {
        "student_name":"Abdul Mannan",
        "class":"9c",
        "father_name":"Abdul Majid",
        "contact":"03456025527",
        "group":"Medical",
        "gender":"Male",
        "profile":"",
    },
    {
        "student_name":"Naima Siddique",
        "class":"9a",
        "father_name":"Furqan Siddique",
        "contact":"03456025527",
        "group":"Computer Science",
        "gender":"Female",
        "profile":"",
    },
    {
        "student_name":"Muhammad Aseer",
        "class":"10a",
        "father_name":"Abdul Rasheed",
        "contact":"03456025527",
        "group":"Computer Science",
        "gender":"Male",
        "profile":"",
    },
    {
        "student_name":"Furqan Rasheed",
        "class":"10b",
        "father_name":"Rasheed Khan",
        "contact":"03456025527",
        "group":"Medical",
        "gender":"Male",
        "profile":"",
    },
    {
        "student_name":"Tooba Irshad",
        "class":"10c",
        "father_name":"Irshad Kazmi",
        "contact":"03456025527",
        "group":"Humanity",
        "gender":"Female",
        "profile":"",
    },
    
]
